### ISSUE TITLE
Time for production

### ISSUE THREAD

**Issue by siwelisabeth** [gbif/hp-living-norway#27]
Hi @MortenHofft,

We are planning to put the first version of our hosted portal into production soon, i.e. on monday 4. April. The plan is to do it silently and then promote it after it has been up an running for a little time. What do you think about that, is that something that is ok with you? What are the actions required from our side in order to put it into production? I remember having seen a page where the steps on how to prepare for a release were described but now I can not find it, sorry for that. 

If we need to do changes after the first release (bugs etc) - what is the process? If we want to publish only news (and not a new version of the portal), what is the process? Maybe this is described in the release instruction document or somewhere else?

We still need to do some code changes, but will hopefully be done with that within a couple of days.

**Comment by MortenHofft** [comment]
Hi @siwelisabeth - Sorry for the slow response, I'm just back from vacation and will be offline much of this and coming week as well.

You need a domain name and we need to set it up. @MattBlissett can help you with that part. Here is some preparatory reading
https://github.com/gbif/hosted-portals/blob/main/getting-started/domain-name.md

And you need to sign a hosting agreement. @timrobertson100 can help you with that, that part it is probably best handled by email https://www.gbif.org/contact-us/directory?personId=22

As for how you release this:
* I think it sounds sensible to get it into production and see that it all works as expected. That gives you time to find bugs and like hardcoded environments e.g. https://github.com/gbif/hp-living-norway/blob/fe07bad6b2ddf228061af5c5a0248ce0f29a575b/_includes/datasets.html#L140 (which should probably point to prod when in prod)
* Any change you do to master gets deployed to your staging environment. Just like now. To deploy to production you need to do a release. No matter how big or small the change. No matter if it is a Javascript change or a content (markdown) typo fix.

**Comment by siwelisabeth** [comment]
Hei @Morten, thank you for your reply. Maybe a stupid question, sorry for that, but how do we do the release? Can we do it on our own or do we need help from you?

**Comment by frafra** [comment]
Do you mean a release here on GitHub, associated with a git tag?

**Comment by MortenHofft** [comment]
> Do you mean making a release here on GitHub, associated with a git tag?

Yes just a Github release https://github.com/gbif/hp-living-norway/releases/new

**Comment by MattBlissett** [comment]
Yes, exactly.

But please sign the hosting agreement first, Tim will send it later today.

**Comment by frafra** [comment]
A first release has been made. Can we close this issue?
I think we could just need to remove the `-staging` from the GraphQL GBIF URLs.

**Comment by frafra** [comment]
We do not rely on the `-staging` GraphQL API (and we can even could even [avoid using GraphQL actually](https://github.com/gbif/hp-living-norway/issues/38)).

I will close this issue, as we had multiple releases and the agreement has been signed.
