### ISSUE TITLE
R code for downloading data - tab

### ISSUE THREAD

**Issue by DrMattG** [gbif/hp-living-norway#28]
The code is here: https://gist.github.com/DrMattG/93f740e90e502c83130dbadfdf10fd88
We use the term datasetKey in the code - is that the correct word? If not I can change it quickly.

**Comment by siwelisabeth** [comment]
@DrMattG Thank you. I think datasetKey will work fine. Then I just replace all the datasetKey guids in the code with the one from the current dataset?

**Comment by DrMattG** [comment]
Yes exactly! Thanks (I see that I have used two keys for different datasets in the example - I think just replacing them all makes sense... sorry I was tired!)

**Comment by siwelisabeth** [comment]
Great :-) I will send you a notice when it is in the staging environment in the portal, so you can take a look :-)

**Comment by siwelisabeth** [comment]
@DrMattG Your R-code is on the portal :-) https://hp-living-norway.gbif-staging.org/ - you find it on a dataset page, the R code tab. Please let me know if you want some changes or if you see something that is not as it should be.
