### ISSUE TITLE
Domain for Living Norway hosted portal

### ISSUE THREAD

**Issue by siwelisabeth** [gbif/hp-living-norway#31]
Hi @MattBlissett 

The domain for our hosted portal is:  data.livingnorway.no

**Comment by siwelisabeth** [comment]
Hi @MattBlissett,

The Living Norway portal is now published and our IT department has created a single CNAME record for our subdomain (data.livingnorway.no) to point to hosted-portal.gbif.org, as described in the document above. When we go to data.livingnorway.no we are redirected to gbif. Do you have any ideas on what is missing?

**Comment by MattBlissett** [comment]
Hi,

There is a manual step after the DNS is changed -- I need to generate the TLS certificate.  It should be working now.

**Comment by siwelisabeth** [comment]
Thank you very much :-)
